config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'pages/contact'
  get 'pages/portfolio'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def contact

  end 

  def portfolio

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'home.css', media: 'all' %>
    <%= stylesheet_link_tag 'contact.css', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="nav">
      <h3><%= link_to "Check out my Photography", "https://www.modelmayhem.com/4704027" %></h3>
      <%# <h2>Logo</h2> %>
      <ul class="navlist">
        <li><%= link_to "Home", root_path, class: "nav-link" %></li>
        <li><%= link_to "Portfolio", pages_portfolio_path, class: "nav-link" %></li>
        <li><%= link_to "Contact", pages_contact_path, class: "nav-link" %></li>
      </ul>
      <div class="burger">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </div>
    </div>
    
    <footer>
      <ul class="socials">
        <li class="sociallinks"><%= link_to "Facebook", "http://www.facebook.com/Spartan626" %></li>
        <li class="sociallinks"><%= link_to "Instagram", "http://www.instagram.com/mileup_photo/" %></li>
        <li class="sociallinks"><%= link_to "LinkedIn", "https://www.linkedin.com/in/kyle-williamson-dev/" %></li>
        <li class="sociallinks"><%= link_to "Pinterest", "https://www.pinterest.com/theactualkyle/" %></li>
      </ul>
    </footer>

    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Send me an iquiry!</h1>
<p>Contact form page</p>

app/views/pages/home.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h2 id="myname">Kyle Williamson</h2>
    <br>
    <p id="mytitle">Web Developer</p>
    <br>
    <br>
    <%= link_to "Hire me", pages_contact_path, class: "hireme" %>
  </div>
</div>

<div class="about-me">
  <div class="about-content">
    <h2 id="about-h2">A little about me...</h2>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
      reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
      deserunt mollit anim id est laborum.</p>
  </div>
  <div class="my-photo">
    <p>Photo of me</p>
  </div>
</div>

  

app/views/pages/portfolio.html.erb
<h1>My Portfolio</h1>
<p>This is a page where multiple websites will be displayed and linked</p>